#! /usr/bin/env python3

"""Launch csvedit GUI.
"""

import sys

from PySide.QtGui import QApplication, QMainWindow
from csvedit_mod.ui.mainwindow import Ui_MainWindow

def main():
    """Main program."""
    app = QApplication(sys.argv)
    ui = Ui_MainWindow()
    mainwin = QMainWindow()
    ui.setupUi(mainwin)
    mainwin.show()

    sys.exit(app.exec_())
    return

if __name__ == "__main__":
    main()
