#! /usr/bin/env python3

"""DESCRIPTION
"""

import sys
import argparse

import csvedit_mod

def main(options):
    """Main program."""
    # MAIN_LOGIC
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
        description="DESCRIPTION",
    )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
