#! /usr/bin/env python3

"""Launch csvedit GUI.
"""

import sys

from PySide.QtGui import QApplication, QMainWindow
from csvedit_mod.main_window import MainWindow

def main():
    """Main program."""
    app = QApplication(sys.argv)
    mainwin = MainWindow()
    mainwin.show()

    sys.exit(app.exec_())
    return

if __name__ == "__main__":
    main()
